// ============================================
// BASE DE DATOS DE PALABRAS - PISTAS SUTILES
// ============================================

const WORDS_WITH_HINTS = {
    animales: {
        name: "🐾 Animales",
        words: [
            { word: "Elefante", hints: ["Memoria prodigiosa", "Safari", "Muy pesado", "Orejas grandes", "Sabana"] },
            { word: "Delfín", hints: ["Acuático social", "Muy listo", "Acuario", "Nariz especial", "Flipper"] },
            { word: "Águila", hints: ["Majestuosa", "Símbolo nacional", "Alturas", "Depredador aéreo", "Visión perfecta"] },
            { word: "Serpiente", hints: ["Sin extremidades", "Fría al tacto", "Silenciosa", "Veneno", "Hipnótica"] },
            { word: "Canguro", hints: ["Boxeador natural", "Oceanía", "Bolsillo natural", "Saltarín", "Outback"] },
            { word: "Pingüino", hints: ["Traje elegante", "Antártida", "Torpeza terrestre", "Colonia", "Frío extremo"] },
            { word: "Tigre", hints: ["Rayas únicas", "Solitario", "Selva asiática", "Grandes felinos", "Peligroso"] },
            { word: "Jirafa", hints: ["Altura récord", "Manchas", "Lengua larga", "Cuello", "Acacia"] },
            { word: "Cocodrilo", hints: ["Pantano", "Lágrimas falsas", "Escamas duras", "Emboscada", "Prehistórico"] },
            { word: "Murciélago", hints: ["Cueva", "Invertido", "Radar natural", "Vampiro", "Nocturno"] },
            { word: "León", hints: ["Melena dorada", "Orgullo", "Sabana africana", "Rugido", "Perezoso"] },
            { word: "Oso", hints: ["Hibernación", "Bosque", "Garras potentes", "Salmón", "Peluche"] },
            { word: "Mono", hints: ["Primate", "Imitador", "Selva", "Travesuras", "Evolución"] },
            { word: "Lobo", hints: ["Manada", "Aullido nocturno", "Caperucita", "Bosque", "Alfa"] },
            { word: "Tiburón", hints: ["Aleta dorsal", "Depredador oceánico", "Semana especial TV", "Dientes afilados", "Miedo"] },
            { word: "Caballo", hints: ["Equitación", "Salvaje oeste", "Carrera", "Noble", "Granja"] },
            { word: "Perro", hints: ["Fiel", "Mascota común", "Ladrido", "Paseo", "Domesticado"] },
            { word: "Gato", hints: ["Independiente", "Maullido", "Curiosidad", "Arañazo", "Egipto antiguo"] },
            { word: "Tortuga", hints: ["Lentitud", "Longevidad", "Protección dura", "Ninja", "Galápagos"] },
            { word: "Conejo", hints: ["Pascua", "Madriguera", "Fertilidad", "Suave", "Zanahoria"] },
            { word: "Ballena", hints: ["Gigante oceánico", "Canto", "Respiración", "Joroba", "Migración"] },
            { word: "Pulpo", hints: ["Ocho brazos", "Tinta", "Inteligente", "Camuflaje", "Tentáculos"] },
            { word: "Araña", hints: ["Ocho patas", "Red", "Pequeño terror", "Rincones", "Tela"] },
            { word: "Abeja", hints: ["Colmena", "Dulce producto", "Zumbido", "Reina", "Polen"] },
            { word: "Mariposa", hints: ["Transformación", "Colorida", "Efímera", "Migración monarca", "Jardín"] },
            { word: "Cebra", hints: ["Rayas blancas y negras", "Paso peatonal", "África", "Caballo salvaje", "Safari"] },
            { word: "Hipopótamo", hints: ["Río africano", "Boca enorme", "Peligroso", "Pesado", "Territorial"] },
            { word: "Rinoceronte", hints: ["Cuerno valioso", "Piel gruesa", "En peligro", "África/Asia", "Carga"] },
            { word: "Gorila", hints: ["Primate grande", "Espalda plateada", "Fuerza", "Selva", "King Kong"] },
            { word: "Leopardo", hints: ["Manchas", "Árbol", "Sigiloso", "Rápido", "Camuflaje"] },
            { word: "Foca", hints: ["Ártico", "Bigotes", "Circo", "Pescado", "Hielo"] },
            { word: "Ciervo", hints: ["Astas", "Bambi", "Bosque", "Navidad", "Tímido"] },
            { word: "Zorro", hints: ["Astuto", "Cola esponjosa", "Fábulas", "Naranja", "Nocturno"] },
            { word: "Búho", hints: ["Nocturno", "Cabeza giratoria", "Sabiduría", "Silencioso", "Grandes ojos"] },
            { word: "Loro", hints: ["Imitador de voz", "Colorido", "Pirata", "Tropical", "Parlanchín"] },
            { word: "Flamenco", hints: ["Rosa", "Una pata", "Elegante", "Caribe", "Cuello curvo"] },
            { word: "Koala", hints: ["Australia", "Eucalipto", "Dormilón", "Tierno", "Árbol"] },
            { word: "Panda", hints: ["Bambú", "China", "Blanco y negro", "Perezoso", "En peligro"] },
            { word: "Camello", hints: ["Joroba", "Desierto", "Resistente", "Caravana", "Agua almacenada"] },
            { word: "Hormiga", hints: ["Colonia", "Trabajadora", "Fuerza", "Pequeña", "Organizada"] }
        ]
    },
    profesiones: {
        name: "👔 Profesiones",
        words: [
            { word: "Astronauta", hints: ["Gravedad cero", "Traje especial", "NASA", "Estrellas", "Cohete"] },
            { word: "Chef", hints: ["Estrella Michelin", "Gorro alto", "Cocina profesional", "Recetas", "Cuchillos"] },
            { word: "Detective", hints: ["Misterios", "Lupa", "Casos", "Sherlock", "Investigación"] },
            { word: "Piloto", hints: ["Cabina", "Vuelo", "Uniforme", "Aterrizaje", "Cielos"] },
            { word: "Cirujano", hints: ["Quirófano", "Bisturí", "Operación", "Precisión", "Bata verde"] },
            { word: "Arquitecto", hints: ["Planos", "Edificios", "Diseño", "Estructuras", "Maquetas"] },
            { word: "Bombero", hints: ["Emergencias", "Manguera", "Rescate", "Sirena", "Fuego"] },
            { word: "Veterinario", hints: ["Clínica animal", "Mascotas", "Vacunas", "Cuidado", "Animales enfermos"] },
            { word: "Abogado", hints: ["Tribunal", "Leyes", "Defensa", "Juicio", "Toga"] },
            { word: "Fotógrafo", hints: ["Cámara", "Luz", "Momentos", "Enfoque", "Exposición"] },
            { word: "Profesor", hints: ["Aula", "Pizarra", "Alumnos", "Lecciones", "Exámenes"] },
            { word: "Médico", hints: ["Consulta", "Diagnóstico", "Pacientes", "Receta", "Estetoscopio"] },
            { word: "Policía", hints: ["Patrulla", "Placa", "Orden", "Uniforme azul", "Sirena"] },
            { word: "Carpintero", hints: ["Madera", "Sierra", "Muebles", "Clavos", "Taller"] },
            { word: "Electricista", hints: ["Cables", "Voltaje", "Instalación", "Cortocircuito", "Enchufe"] },
            { word: "Plomero", hints: ["Tuberías", "Fugas", "Herramientas", "Agua", "Desagüe"] },
            { word: "Panadero", hints: ["Horno", "Masa", "Madrugada", "Levadura", "Aroma"] },
            { word: "Periodista", hints: ["Noticias", "Entrevistas", "Prensa", "Exclusiva", "Fuentes"] },
            { word: "Dentista", hints: ["Consulta dental", "Torno", "Caries", "Anestesia", "Empaste"] },
            { word: "Cantante", hints: ["Escenario", "Micrófono", "Fans", "Voz", "Gira"] },
            { word: "Actor", hints: ["Escena", "Guion", "Personaje", "Cámara", "Acción"] },
            { word: "Científico", hints: ["Laboratorio", "Experimentos", "Hipótesis", "Descubrimiento", "Bata blanca"] },
            { word: "Programador", hints: ["Código", "Bugs", "Software", "Teclado", "Algoritmo"] },
            { word: "Mecánico", hints: ["Taller", "Motor", "Aceite", "Herramientas", "Reparación"] },
            { word: "Jardinero", hints: ["Plantas", "Poda", "Césped", "Tijeras", "Riego"] },
            { word: "Psicólogo", hints: ["Mente", "Terapia", "Escucha", "Emociones", "Sesión"] },
            { word: "Peluquero", hints: ["Tijeras", "Corte", "Salón", "Peinado", "Secador"] },
            { word: "Camarero", hints: ["Bandeja", "Servicio", "Propina", "Restaurante", "Pedido"] },
            { word: "Taxista", hints: ["Taxímetro", "Ciudad", "Rutas", "Pasajeros", "Calles"] },
            { word: "Bibliotecario", hints: ["Libros", "Silencio", "Préstamos", "Catálogo", "Estanterías"] },
            { word: "Músico", hints: ["Instrumento", "Melodía", "Concierto", "Notas", "Ensayo"] },
            { word: "Pintor", hints: ["Lienzo", "Pincel", "Colores", "Arte", "Galería"] },
            { word: "Escultor", hints: ["Mármol", "Cincel", "Figura", "Arte 3D", "Arcilla"] },
            { word: "Bailarín", hints: ["Coreografía", "Movimiento", "Escenario", "Ritmo", "Zapatillas"] },
            { word: "Agricultor", hints: ["Campo", "Cosecha", "Tractor", "Semillas", "Tierra"] },
            { word: "Pescador", hints: ["Red", "Mar", "Barco", "Anzuelo", "Madrugada"] },
            { word: "Cartero", hints: ["Cartas", "Buzón", "Ruta", "Paquetes", "Uniforme"] },
            { word: "Sastre", hints: ["Tela", "Medidas", "Aguja", "Traje", "Confección"] },
            { word: "Payaso", hints: ["Circo", "Nariz roja", "Risas", "Maquillaje", "Niños"] },
            { word: "Mago", hints: ["Trucos", "Varita", "Ilusión", "Sombrero", "Cartas"] }
        ]
    },
    lugares: {
        name: "🗺️ Lugares",
        words: [
            { word: "Hospital", hints: ["Emergencias", "Batas", "Camillas", "Visitas", "Quirófano"] },
            { word: "Aeropuerto", hints: ["Embarque", "Terminal", "Pasaportes", "Retrasos", "Duty free"] },
            { word: "Biblioteca", hints: ["Silencio", "Estanterías", "Préstamos", "Estudiar", "Catálogo"] },
            { word: "Estadio", hints: ["Gradas", "Afición", "Césped", "Goles", "Conciertos"] },
            { word: "Museo", hints: ["Arte", "Exposición", "Guía", "Historia", "No tocar"] },
            { word: "Parque de atracciones", hints: ["Colas", "Adrenalina", "Algodón", "Diversión", "Montaña rusa"] },
            { word: "Submarino", hints: ["Profundidad", "Periscopio", "Tripulación", "Sonar", "Presión"] },
            { word: "Castillo", hints: ["Medieval", "Torres", "Foso", "Realeza", "Murallas"] },
            { word: "Crucero", hints: ["Camarotes", "Buffet", "Escalas", "Vacaciones", "Cubierta"] },
            { word: "Estación espacial", hints: ["Órbita", "Experimentos", "Ingravidez", "Astronautas", "ISS"] },
            { word: "Playa", hints: ["Arena", "Olas", "Bronceado", "Sombrilla", "Toalla"] },
            { word: "Montaña", hints: ["Cima", "Escalada", "Nieve", "Altitud", "Senderismo"] },
            { word: "Cine", hints: ["Palomitas", "Butacas", "Trailers", "Oscuridad", "Estreno"] },
            { word: "Restaurante", hints: ["Reserva", "Menú", "Cuenta", "Propina", "Mesa"] },
            { word: "Supermercado", hints: ["Carrito", "Pasillos", "Ofertas", "Caja", "Cola"] },
            { word: "Gimnasio", hints: ["Pesas", "Sudor", "Máquinas", "Espejo", "Rutina"] },
            { word: "Zoológico", hints: ["Jaulas", "Safari", "Familias", "Conservación", "Guía"] },
            { word: "Iglesia", hints: ["Campanario", "Misa", "Altar", "Bancos", "Fe"] },
            { word: "Prisión", hints: ["Celdas", "Barrotes", "Guardias", "Patio", "Condena"] },
            { word: "Universidad", hints: ["Campus", "Carreras", "Exámenes", "Graduación", "Biblioteca"] },
            { word: "Farmacia", hints: ["Recetas", "Medicinas", "Cruz", "Guardia", "Mostrador"] },
            { word: "Banco", hints: ["Cajero", "Cuenta", "Préstamo", "Caja fuerte", "Interés"] },
            { word: "Hotel", hints: ["Recepción", "Habitación", "Estrellas", "Servicio", "Check-in"] },
            { word: "Discoteca", hints: ["DJ", "Luces", "Baile", "Noche", "Barra"] },
            { word: "Cementerio", hints: ["Lápidas", "Flores", "Silencio", "Visitas", "Paz"] },
            { word: "Acuario", hints: ["Tanques", "Peces", "Cristal", "Marino", "Tiburones"] },
            { word: "Teatro", hints: ["Escenario", "Telón", "Aplausos", "Obra", "Butacas"] },
            { word: "Estación de tren", hints: ["Andén", "Vías", "Horarios", "Billetes", "Llegadas"] },
            { word: "Gasolinera", hints: ["Surtidor", "Combustible", "Tienda", "Carretera", "Precios"] },
            { word: "Lavandería", hints: ["Ropa", "Máquinas", "Monedas", "Secadora", "Detergente"] },
            { word: "Peluquería", hints: ["Corte", "Espejo", "Sillón", "Revistas", "Tijeras"] },
            { word: "Pizzería", hints: ["Horno", "Masa", "Delivery", "Toppings", "Italiana"] },
            { word: "Panadería", hints: ["Horno", "Aroma", "Pan", "Mostrador", "Madrugada"] },
            { word: "Carnicería", hints: ["Carne", "Mostrador frío", "Cuchillos", "Cortes", "Báscula"] },
            { word: "Frutería", hints: ["Fresco", "Temporada", "Colores", "Báscula", "Vitaminas"] },
            { word: "Óptica", hints: ["Gafas", "Examen visual", "Lentes", "Monturas", "Graduación"] },
            { word: "Veterinaria", hints: ["Mascotas", "Consulta", "Vacunas", "Animales", "Jaulas"] },
            { word: "Parque", hints: ["Bancos", "Árboles", "Paseo", "Niños", "Palomas"] },
            { word: "Piscina", hints: ["Cloro", "Flotador", "Socorrista", "Vestuario", "Carril"] },
            { word: "Spa", hints: ["Relax", "Masaje", "Sauna", "Tratamiento", "Bienestar"] }
        ]
    },
    peliculas: {
        name: "🎬 Películas/Series",
        words: [
            { word: "Titanic", hints: ["1912", "Océano", "Trágico", "Romance", "Iceberg"] },
            { word: "Star Wars", hints: ["Galaxia", "Sables", "Imperio", "Fuerza", "Saga espacial"] },
            { word: "Harry Potter", hints: ["Magia", "Escuela especial", "Cicatriz", "Varita", "Reino Unido"] },
            { word: "El Padrino", hints: ["Familia italiana", "Clásico", "Oferta", "Crimen", "Don"] },
            { word: "Jurassic Park", hints: ["Isla", "ADN antiguo", "Caos", "Parque", "90s"] },
            { word: "Matrix", hints: ["Simulación", "Elección", "Balas lentas", "Realidad", "Neo"] },
            { word: "Avatar", hints: ["Azul", "Planeta lejano", "3D pionero", "Naturaleza", "Conexión"] },
            { word: "Frozen", hints: ["Hielo", "Hermanas", "Canción pegadiza", "Disney", "Reino nórdico"] },
            { word: "Breaking Bad", hints: ["Química", "Desierto", "Transformación", "Familia", "Azul"] },
            { word: "Stranger Things", hints: ["80s", "Niños", "Dimensión", "Poderes", "Pueblo pequeño"] },
            { word: "El Rey León", hints: ["Sabana", "Herencia", "Tío malvado", "Animado clásico", "Círculo"] },
            { word: "Toy Story", hints: ["Animación", "Vaquero", "Habitación infantil", "Pixar", "Amistad"] },
            { word: "Los Vengadores", hints: ["Equipo", "Superhéroes", "Marvel", "Amenaza global", "Unidos"] },
            { word: "El Señor de los Anillos", hints: ["Fantasía épica", "Joya", "Viaje", "Pequeños héroes", "Trilogía"] },
            { word: "Piratas del Caribe", hints: ["Mar", "Tesoro", "Brújula", "Capitán excéntrico", "Maldición"] },
            { word: "Shrek", hints: ["Pantano", "Verde", "Cuento de hadas", "Comedia animada", "Princesa"] },
            { word: "La Casa de Papel", hints: ["Atraco", "Planificación", "España", "Máscaras", "Fábrica"] },
            { word: "Game of Thrones", hints: ["Reinos", "Poder", "Invierno", "Fantasía medieval", "HBO"] },
            { word: "Friends", hints: ["Cafetería", "Nueva York", "6 amigos", "Sitcom", "90s"] },
            { word: "The Office", hints: ["Oficina", "Documental falso", "Jefe incómodo", "Papelería", "Comedia"] },
            { word: "Batman", hints: ["Gotham", "Murciélago", "Noche", "Huérfano rico", "Justicia"] },
            { word: "Spider-Man", hints: ["Nueva York", "Adolescente", "Poderes arácnidos", "Responsabilidad", "Tela"] },
            { word: "Indiana Jones", hints: ["Arqueología", "Aventura", "Sombrero", "Reliquias", "Látigo"] },
            { word: "ET", hints: ["Alienígena", "Niño", "80s", "Bicicleta", "Teléfono"] },
            { word: "Coco", hints: ["México", "Familia", "Música", "Tradición", "Recuerdos"] },
            { word: "Interestelar", hints: ["Espacio", "Tiempo", "Padre e hija", "Agujero negro", "Supervivencia"] },
            { word: "Inception", hints: ["Sueños", "Capas", "Trompo", "Mente", "Arquitecta"] },
            { word: "Joker", hints: ["Villano", "Risas", "Gotham", "Transformación", "Solitario"] },
            { word: "Gladiador", hints: ["Roma", "Arena", "Venganza", "General", "Espectáculo"] },
            { word: "Forrest Gump", hints: ["Correr", "Historia americana", "Chocolates", "Pluma", "Inocencia"] },
            { word: "El Resplandor", hints: ["Hotel", "Invierno", "Locura", "Terror", "Aislamiento"] },
            { word: "Tiburón", hints: ["Playa", "Verano", "Miedo al agua", "Música tensa", "70s"] },
            { word: "Regreso al Futuro", hints: ["Tiempo", "Coche especial", "80s", "Científico loco", "Adolescente"] },
            { word: "Pulp Fiction", hints: ["No lineal", "Maletín", "Tarantino", "Diálogos", "90s"] },
            { word: "El Club de la Pelea", hints: ["Reglas", "Jabón", "Alter ego", "Fincher", "Insomnio"] },
            { word: "Squid Game", hints: ["Juegos infantiles", "Corea", "Dinero", "Supervivencia", "Netflix"] },
            { word: "Money Heist", hints: ["Atraco", "Planificación", "España", "Nombres de ciudades", "Resistencia"] },
            { word: "The Mandalorian", hints: ["Casco", "Bebé verde", "Cazarrecompensas", "Galaxia", "Disney+"] },
            { word: "Peaky Blinders", hints: ["Gorras", "Familia", "Birmingham", "Posguerra", "Gansters"] },
            { word: "Narcos", hints: ["Colombia", "Droga", "Cartel", "80s", "Pablo"] }
        ]
    },
    comida: {
        name: "🍕 Comida",
        words: [
            { word: "Pizza", hints: ["Redonda", "Horno", "Toppings", "Italia", "Delivery popular"] },
            { word: "Sushi", hints: ["Japón", "Crudo", "Palillos", "Enrollado", "Algas"] },
            { word: "Hamburguesa", hints: ["Fast food", "Pan redondo", "Carne picada", "Americana", "Cadenas"] },
            { word: "Paella", hints: ["Arroz", "Sartén grande", "Valencia", "Mariscos", "Azafrán"] },
            { word: "Tacos", hints: ["México", "Doblado", "Salsa", "Cilantro", "Street food"] },
            { word: "Croissant", hints: ["Francia", "Mantequilla", "Hojaldre", "Media luna", "Desayuno"] },
            { word: "Ramen", hints: ["Japón", "Caldo", "Fideos", "Huevo", "Caliente"] },
            { word: "Lasaña", hints: ["Capas", "Italia", "Horno", "Boloñesa", "Gratinada"] },
            { word: "Ceviche", hints: ["Perú", "Cítrico", "Marinado", "Pescado", "Fresco"] },
            { word: "Curry", hints: ["India", "Especias", "Amarillo", "Picante", "Con arroz"] },
            { word: "Hot Dog", hints: ["Estadio", "Pan alargado", "Mostaza", "NY", "Salchicha"] },
            { word: "Helado", hints: ["Frío", "Cono", "Verano", "Cremoso", "Sabores"] },
            { word: "Chocolate", hints: ["Cacao", "Dulce", "Suizo", "Se derrite", "Marrón"] },
            { word: "Tortilla española", hints: ["Huevo", "Redonda", "España", "Patata", "Bocadillo"] },
            { word: "Pasta", hints: ["Italia", "Carbohidratos", "Salsa", "Al dente", "Formas"] },
            { word: "Arroz", hints: ["Grano", "Asia", "Básico", "Hervido", "Blanco"] },
            { word: "Ensalada", hints: ["Verde", "Ligera", "Aliño", "Cruda", "Saludable"] },
            { word: "Pan", hints: ["Horno", "Básico", "Masa", "Corteza", "Miga"] },
            { word: "Huevo frito", hints: ["Sartén", "Amarillo centro", "Aceite", "Desayuno", "Rápido"] },
            { word: "Galletas", hints: ["Dulce", "Crujiente", "Horneado", "Chispas", "Merienda"] },
            { word: "Empanada", hints: ["Rellena", "Masa cerrada", "Horno o frita", "Argentina", "Media luna"] },
            { word: "Churros", hints: ["España", "Chocolate", "Frito", "Azúcar", "Alargado"] },
            { word: "Pancakes", hints: ["América", "Sirope", "Apilados", "Desayuno", "Redondos"] },
            { word: "Pollo frito", hints: ["Crujiente", "Empanizado", "Sur USA", "Cadenas", "Alitas"] },
            { word: "Donut", hints: ["Agujero", "Glaseado", "América", "Simpson", "Dulce"] },
            { word: "Burrito", hints: ["México", "Enrollado", "Grande", "Frijoles", "Tex-mex"] },
            { word: "Croquetas", hints: ["Rebozadas", "España", "Bechamel", "Fritas", "Tapas"] },
            { word: "Gazpacho", hints: ["Frío", "Tomate", "Andalucía", "Verano", "Líquido"] },
            { word: "Falafel", hints: ["Oriente medio", "Garbanzos", "Vegetariano", "Frito", "Pita"] },
            { word: "Guacamole", hints: ["Verde", "México", "Aguacate", "Dip", "Nachos"] },
            { word: "Tiramisú", hints: ["Italia", "Café", "Capas", "Postre", "Mascarpone"] },
            { word: "Brownie", hints: ["Chocolate", "Cuadrado", "Denso", "América", "Nueces"] },
            { word: "Kebab", hints: ["Turquía", "Carne giratoria", "Pan pita", "Salsa", "Nocturno"] },
            { word: "Dim Sum", hints: ["China", "Pequeñas porciones", "Vapor", "Cantonés", "Té"] },
            { word: "Parrillada", hints: ["Carne", "Fuego", "Argentina", "BBQ", "Asado"] },
            { word: "Fondue", hints: ["Suiza", "Derretido", "Pincho", "Queso", "Compartir"] },
            { word: "Crepes", hints: ["Francia", "Fino", "Dulce o salado", "Plancha", "Relleno"] },
            { word: "Nachos", hints: ["México", "Crujiente", "Queso", "Jalapeños", "Compartir"] },
            { word: "Sopa", hints: ["Caliente", "Cuchara", "Caldo", "Invierno", "Reconfortante"] },
            { word: "Tarta", hints: ["Cumpleaños", "Dulce", "Velas", "Celebración", "Porciones"] }
        ]
    },
    deportes: {
        name: "⚽ Deportes",
        words: [
            { word: "Fútbol", hints: ["Goles", "Equipos de 11", "Mundial", "Popular global", "Estadio"] },
            { word: "Baloncesto", hints: ["Aro", "Dribling", "NBA", "Alto", "Cancha"] },
            { word: "Natación", hints: ["Agua", "Cronómetro", "Estilos", "Piscina", "Carriles"] },
            { word: "Tenis", hints: ["Raqueta", "Set", "Individual o dobles", "Tierra batida", "Saque"] },
            { word: "Golf", hints: ["Hoyos", "Green", "Carrito", "Silencio", "Swing"] },
            { word: "Boxeo", hints: ["Ring", "Guantes", "Rounds", "Esquina", "Peso"] },
            { word: "Ciclismo", hints: ["Dos ruedas", "Tour", "Pelotón", "Etapas", "Subida"] },
            { word: "Surf", hints: ["Olas", "Tabla", "Costa", "Equilibrio", "Wax"] },
            { word: "Escalada", hints: ["Vertical", "Cuerda", "Roca", "Agarre", "Altura"] },
            { word: "Esgrima", hints: ["Florete", "Tocado", "Máscara", "Elegante", "Francés"] },
            { word: "Atletismo", hints: ["Pista", "Carreras", "Saltos", "Lanzamientos", "Récords"] },
            { word: "Voleibol", hints: ["Red", "Remate", "Seis", "Rotación", "Playa"] },
            { word: "Béisbol", hints: ["Bate", "Bases", "Innings", "América", "Guante"] },
            { word: "Hockey", hints: ["Palo", "Disco", "Hielo o césped", "Portero", "Contacto"] },
            { word: "Rugby", hints: ["Ovalado", "Tackle", "Try", "Scrum", "Sin protección"] },
            { word: "Karate", hints: ["Japonés", "Kata", "Cinturón", "Golpes", "Dojo"] },
            { word: "Judo", hints: ["Agarre", "Proyección", "Tatami", "Olimpico", "Gi blanco"] },
            { word: "Esquí", hints: ["Nieve", "Bastones", "Descenso", "Remonte", "Invierno"] },
            { word: "Patinaje", hints: ["Cuchillas", "Pirueta", "Hielo", "Música", "Artístico"] },
            { word: "Gimnasia", hints: ["Aparatos", "Rutina", "Puntuación", "Flexibilidad", "Acrobacia"] },
            { word: "Fórmula 1", hints: ["Circuito", "Boxes", "Pole", "Monoplaza", "Gran Premio"] },
            { word: "MotoGP", hints: ["Dos ruedas", "Circuito", "Inclinación", "Velocidad", "Casco"] },
            { word: "Halterofilia", hints: ["Peso", "Barra", "Levantamiento", "Fuerza", "Olímpico"] },
            { word: "Triatlón", hints: ["Tres pruebas", "Resistencia", "Transición", "Ironman", "Extremo"] },
            { word: "Ajedrez", hints: ["Tablero", "Estrategia", "Jaque", "Piezas", "Mental"] },
            { word: "Bádminton", hints: ["Pluma", "Red", "Raqueta ligera", "Asia", "Volea"] },
            { word: "Críquet", hints: ["Bate", "Wicket", "Inglaterra", "India", "Lento"] },
            { word: "Polo", hints: ["Caballo", "Mazo", "Elite", "Argentina", "Campo grande"] },
            { word: "Waterpolo", hints: ["Piscina", "Portería", "Equipos", "Natación", "Balón"] },
            { word: "Snowboard", hints: ["Nieve", "Tabla única", "Halfpipe", "Invierno", "X Games"] },
            { word: "Skateboard", hints: ["Tabla", "Trucos", "Rampa", "Urbano", "Ruedas pequeñas"] },
            { word: "Parkour", hints: ["Urbano", "Saltos", "Obstáculos", "Fluidez", "Acrobático"] },
            { word: "Crossfit", hints: ["Intenso", "Box", "WOD", "Funcional", "Comunidad"] },
            { word: "Yoga", hints: ["Flexibilidad", "Respiración", "Posturas", "Mente", "India"] },
            { word: "Pilates", hints: ["Core", "Control", "Reformer", "Alemán", "Elongación"] },
            { word: "Paddle", hints: ["Pala", "Cristal", "Parejas", "España", "Rebote"] },
            { word: "Squash", hints: ["Pared", "Raqueta", "Cerrado", "Intenso", "Pelota pequeña"] },
            { word: "Dardos", hints: ["Diana", "Pub", "Precisión", "Triple 20", "Inglaterra"] },
            { word: "Billar", hints: ["Mesa verde", "Taco", "Bolas", "Troneras", "Carambola"] },
            { word: "Bolos", hints: ["Pista", "Bola pesada", "Pins", "Strike", "Zapatos especiales"] }
        ]
    },
    tecnologia: {
        name: "💻 Tecnología",
        words: [
            { word: "Smartphone", hints: ["Bolsillo", "Táctil", "Apps", "Siempre conectado", "Notificaciones"] },
            { word: "Dron", hints: ["Aéreo", "Control remoto", "Cámara", "Hélices", "Vista superior"] },
            { word: "Robot", hints: ["Autómata", "Programado", "Tareas", "Futuro", "Brazos mecánicos"] },
            { word: "Realidad Virtual", hints: ["Inmersivo", "Gafas", "360°", "Simulación", "Otro mundo"] },
            { word: "Inteligencia Artificial", hints: ["Aprende", "Algoritmos", "Datos", "Automático", "Predicción"] },
            { word: "Blockchain", hints: ["Descentralizado", "Cadena", "Cripto", "Inmutable", "Seguro"] },
            { word: "Impresora 3D", hints: ["Capas", "Plástico", "Diseño", "Fabricación", "Prototipo"] },
            { word: "Tesla", hints: ["Eléctrico", "Autopilot", "Moderno", "Sin gasolina", "Lujoso"] },
            { word: "Netflix", hints: ["Streaming", "Series", "Suscripción", "Maratón", "Original"] },
            { word: "TikTok", hints: ["Corto", "Viral", "Baile", "Jóvenes", "Scroll infinito"] },
            { word: "YouTube", hints: ["Vídeos", "Creadores", "Viral", "Tutoriales", "Gratis"] },
            { word: "Instagram", hints: ["Fotos", "Stories", "Filtros", "Cuadrado", "Influencers"] },
            { word: "WhatsApp", hints: ["Verde", "Mensajes", "Grupos", "Llamadas", "Ubicuo"] },
            { word: "WiFi", hints: ["Inalámbrico", "Conexión", "Contraseña", "Router", "Señal"] },
            { word: "USB", hints: ["Puerto", "Datos", "Almacenamiento", "Universal", "Pen"] },
            { word: "GPS", hints: ["Ubicación", "Navegación", "Satélite", "Ruta", "Perdido"] },
            { word: "Laptop", hints: ["Portátil", "Trabajo", "Batería", "Teclado", "Ligero"] },
            { word: "Tablet", hints: ["Pantalla grande", "Entre dos", "iPad", "Táctil", "Lectura"] },
            { word: "Spotify", hints: ["Música", "Playlists", "Streaming", "Premium", "Descubrimiento"] },
            { word: "Amazon", hints: ["E-commerce", "Envío rápido", "Todo", "Prime", "Gigante"] },
            { word: "PlayStation", hints: ["Consola", "Gaming", "Sony", "Mando", "Exclusivos"] },
            { word: "Nintendo", hints: ["Japonés", "Familiar", "Portátil", "Nostalgia", "Mario"] },
            { word: "Alexa", hints: ["Voz", "Asistente", "Casa", "Altavoz", "Comandos"] },
            { word: "Cámara digital", hints: ["Fotos", "Sensor", "Memoria", "Zoom", "Sin película"] },
            { word: "Auriculares inalámbricos", hints: ["Bluetooth", "Sin cables", "Oídos", "Música", "Portátil"] },
            { word: "Smartwatch", hints: ["Muñeca", "Notificaciones", "Salud", "Pasos", "Conectado"] },
            { word: "Kindle", hints: ["Lectura", "E-ink", "Libros", "Amazon", "Sin brillo"] },
            { word: "Twitch", hints: ["Streaming", "Gamers", "Chat", "Directo", "Subs"] },
            { word: "Discord", hints: ["Comunidad", "Servidores", "Voz", "Gaming", "Canales"] },
            { word: "Zoom", hints: ["Videoconferencia", "Pandemia", "Reuniones", "Pantalla compartida", "Mute"] },
            { word: "ChatGPT", hints: ["IA conversacional", "Texto", "Respuestas", "OpenAI", "Ayuda"] },
            { word: "Bitcoin", hints: ["Cripto", "Minería", "Volatile", "Digital", "Descentralizado"] },
            { word: "Google", hints: ["Búsqueda", "Omnipresente", "Datos", "Publicidad", "Gigante tech"] },
            { word: "Apple", hints: ["Manzana tech", "Premium", "Ecosistema", "Diseño", "Innovación"] },
            { word: "Microsoft", hints: ["Windows", "Office", "Corporativo", "Gates", "Xbox"] },
            { word: "VPN", hints: ["Privacidad", "Túnel", "Ubicación falsa", "Seguridad", "Encriptado"] },
            { word: "SSD", hints: ["Rápido", "Almacenamiento", "Sin partes móviles", "Silencioso", "Estado sólido"] },
            { word: "4K", hints: ["Resolución", "Píxeles", "Ultra HD", "Nitidez", "Pantallas"] },
            { word: "Podcast", hints: ["Audio", "Episodios", "Suscripción", "Voces", "En movimiento"] },
            { word: "Criptomoneda", hints: ["Digital", "Volátil", "Wallet", "Descentralizado", "Minería"] }
        ]
    },
    famosos: {
        name: "⭐ Famosos",
        words: [
            { word: "Messi", hints: ["Argentina", "Pequeño genio", "París luego Miami", "GOAT debate", "Copas del mundo"] },
            { word: "Cristiano Ronaldo", hints: ["Portugal", "Físico", "Goleador", "Arabia", "Siuuu"] },
            { word: "Taylor Swift", hints: ["Pop country", "Eras", "Swifties", "Ex novios canciones", "Billonaria"] },
            { word: "Bad Bunny", hints: ["Puerto Rico", "Latino", "Gafas", "Colaboraciones", "Controversial"] },
            { word: "Shakira", hints: ["Colombia", "Caderas", "Latina", "Waka Waka", "Piqué"] },
            { word: "Elon Musk", hints: ["Tech", "Twitter X", "Coches eléctricos", "Espacio", "Polémico"] },
            { word: "Beyoncé", hints: ["Queen B", "Diva", "Formation", "Jay-Z", "Destiny"] },
            { word: "Michael Jackson", hints: ["Rey", "80s", "Baile", "Neverland", "Legado"] },
            { word: "Madonna", hints: ["Material", "80s", "Reinvención", "Provocadora", "Pop queen"] },
            { word: "Ronaldinho", hints: ["Brasil", "Sonrisa", "Magia", "Fiesta", "Barcelona"] },
            { word: "Maradona", hints: ["Argentina", "Mano", "Nápoles", "10", "Leyenda"] },
            { word: "Rihanna", hints: ["Barbados", "Fenty", "Super Bowl", "Umbrella", "Moda"] },
            { word: "Ed Sheeran", hints: ["Británico", "Pelirrojo", "Guitarra", "Baladas", "Shape"] },
            { word: "Kim Kardashian", hints: ["Reality", "Influencer", "Skims", "Familia", "Instagram"] },
            { word: "LeBron James", hints: ["Rey", "NBA", "Cleveland Miami LA", "Negocios", "Longevidad"] },
            { word: "Serena Williams", hints: ["Tenis", "Hermanas", "Grand Slams", "Potencia", "Retirada"] },
            { word: "Usain Bolt", hints: ["Jamaica", "Velocidad", "Récords", "Pose", "Rayo"] },
            { word: "Roger Federer", hints: ["Suizo", "Elegante", "Tenis", "Rivalidades", "Caballero"] },
            { word: "Adele", hints: ["Británica", "Voz", "Hello", "Baladas", "Divorcios"] },
            { word: "Drake", hints: ["Canadá", "Rap", "Toronto", "Views", "Beef"] },
            { word: "Billie Eilish", hints: ["Gen Z", "Susurros", "Verde", "Hermano", "Oscura"] },
            { word: "BTS", hints: ["Corea", "K-pop", "Army", "7", "Global"] },
            { word: "The Weeknd", hints: ["Canadá", "Blinding", "R&B", "Pelo", "Super Bowl"] },
            { word: "Dua Lipa", hints: ["Británica", "Kosovo", "Disco", "Baile", "Levitating"] },
            { word: "Harry Styles", hints: ["One Direction", "Moda", "Brit", "Watermelon", "Género fluido"] },
            { word: "Karol G", hints: ["Colombia", "Reggaetón", "Azul", "Bichota", "Anuel"] },
            { word: "J Balvin", hints: ["Colombia", "Colores", "Reggaetón", "Mi gente", "Moda"] },
            { word: "Travis Scott", hints: ["Houston", "Rap", "Kylie", "Nike", "Cactus"] },
            { word: "Neymar", hints: ["Brasil", "PSG Arabia", "Caro", "Lesiones", "Caídas"] },
            { word: "Mbappé", hints: ["Francia", "Velocidad", "Joven", "PSG Real", "Tortuga"] },
            { word: "Lewis Hamilton", hints: ["F1", "Británico", "Récords", "Mercedes", "Activismo"] },
            { word: "Tom Hanks", hints: ["Hollywood", "Bueno", "Forrest", "Wilson", "Simpático"] },
            { word: "Leonardo DiCaprio", hints: ["Oscar tarde", "Titanic", "Medio ambiente", "Modelos", "Hollywood"] },
            { word: "Oprah", hints: ["Talk show", "Billonaria", "Influencia", "Club libro", "Emporio"] },
            { word: "Dwayne Johnson", hints: ["La Roca", "Wrestling", "Películas", "Músculos", "Tequila"] },
            { word: "Zendaya", hints: ["Disney", "Euphoria", "Moda", "Tom Holland", "Elegante"] },
            { word: "Kylie Jenner", hints: ["Labios", "Cosmetics", "Billonaria joven", "Kardashian", "Stormi"] },
            { word: "Post Malone", hints: ["Tatuajes cara", "Rap pop", "Rockstar", "Cerveza", "Melódico"] },
            { word: "Ariana Grande", hints: ["Voz aguda", "Coleta", "Disney Nick", "Thank u next", "Wicked"] },
            { word: "Rosalía", hints: ["España", "Flamenco urbano", "Motomami", "Rauw", "Experimental"] }
        ]
    },
    objetos: {
        name: "🔧 Objetos",
        words: [
            { word: "Paraguas", hints: ["Días grises", "Plegable", "Olvidable", "Protección", "Mango curvo"] },
            { word: "Reloj", hints: ["Muñeca", "Tiempo", "Segundero", "Alarma", "Puntualidad"] },
            { word: "Tijeras", hints: ["Cortar", "Dos partes", "Manualidades", "Filo", "Mango"] },
            { word: "Espejo", hints: ["Reflejo", "Vanidad", "Cristal", "Baño", "Selfie antiguo"] },
            { word: "Llave", hints: ["Abrir", "Metal", "Bolsillo", "Perdida", "Cerradura"] },
            { word: "Gafas", hints: ["Vista", "Nariz", "Graduación", "Montura", "Leer"] },
            { word: "Lámpara", hints: ["Iluminar", "Noche", "Bombilla", "Mesita", "Interruptor"] },
            { word: "Silla", hints: ["Sentarse", "Ruedas o fija", "Escritorio", "Respaldo", "Patas"] },
            { word: "Mesa", hints: ["Superficie", "Comedor", "Trabajo", "Patas", "Encima"] },
            { word: "Cama", hints: ["Dormir", "Colchón", "Sábanas", "Descanso", "Sueños"] },
            { word: "Televisión", hints: ["Pantalla", "Entretenimiento", "Mando", "Canales", "Sofá"] },
            { word: "Nevera", hints: ["Frío", "Cocina", "Comida", "Motor", "Puerta"] },
            { word: "Lavadora", hints: ["Ropa", "Centrifugado", "Tambor", "Limpieza", "Ciclo"] },
            { word: "Microondas", hints: ["Rápido", "Calentar", "Pitido", "Cocina", "Giratorio"] },
            { word: "Aspiradora", hints: ["Suelo", "Polvo", "Ruido", "Limpieza", "Bolsa"] },
            { word: "Cepillo de dientes", hints: ["Higiene bucal", "Cerdas", "Baño", "Mañana noche", "Manual o eléctrico"] },
            { word: "Jabón", hints: ["Limpiar", "Espuma", "Manos", "Fragancia", "Baño"] },
            { word: "Toalla", hints: ["Secar", "Baño", "Playa", "Absorbente", "Suave"] },
            { word: "Almohada", hints: ["Cabeza", "Dormir", "Blanda", "Relleno", "Funda"] },
            { word: "Mochila", hints: ["Espalda", "Libros", "Viaje", "Correas", "Bolsillos"] },
            { word: "Billetera", hints: ["Dinero", "Tarjetas", "Bolsillo", "Plegable", "Perdida"] },
            { word: "Calcetines", hints: ["Pies", "Par", "Interior zapato", "Algodón", "Se pierden"] },
            { word: "Bufanda", hints: ["Cuello", "Frío", "Invierno", "Lana", "Enrollar"] },
            { word: "Vela", hints: ["Luz", "Cera", "Romántico", "Cumpleaños", "Fuego pequeño"] },
            { word: "Globo", hints: ["Aire", "Fiesta", "Flotar", "Explotar", "Helio"] },
            { word: "Bolígrafo", hints: ["Escribir", "Tinta", "Oficina", "Click", "Bolsillo"] },
            { word: "Cuchara", hints: ["Comer", "Sopa", "Metal", "Curvada", "Cocina"] },
            { word: "Tenedor", hints: ["Comer", "Púas", "Metal", "Mesa", "Pinchar"] },
            { word: "Plato", hints: ["Comida", "Redondo", "Mesa", "Cerámica", "Lavar"] },
            { word: "Vaso", hints: ["Beber", "Cristal", "Agua", "Cilíndrico", "Rompible"] },
            { word: "Sartén", hints: ["Cocinar", "Fuego", "Mango largo", "Metal", "Freír"] },
            { word: "Cuchillo", hints: ["Cortar", "Filo", "Cocina", "Peligroso", "Metal"] },
            { word: "Maleta", hints: ["Viaje", "Ruedas", "Ropa", "Aeropuerto", "Equipaje"] },
            { word: "Anillo", hints: ["Dedo", "Joya", "Compromiso", "Círculo", "Brillante"] },
            { word: "Pulsera", hints: ["Muñeca", "Joya", "Adorno", "Cadena", "Regalo"] },
            { word: "Collar", hints: ["Cuello", "Joya", "Colgante", "Cadena", "Elegante"] },
            { word: "Gorra", hints: ["Cabeza", "Sol", "Visera", "Casual", "Equipo"] },
            { word: "Guantes", hints: ["Manos", "Frío", "Protección", "Par", "Dedos"] },
            { word: "Cinturón", hints: ["Cintura", "Pantalón", "Hebilla", "Cuero", "Ajustar"] },
            { word: "Corbata", hints: ["Cuello", "Formal", "Nudo", "Traje", "Oficina"] }
        ]
    }
};

// Exportar base de datos procesada
export const WORD_DATABASE = {};
for (const [key, category] of Object.entries(WORDS_WITH_HINTS)) {
    WORD_DATABASE[key] = {
        name: category.name,
        words: category.words.map(w => w.word),
        hints: category.words.map(w => w.hints)
    };
}

// Generar código de sala único de 4 letras
export function generateRoomCode() {
    const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
    let code = '';
    for (let i = 0; i < 4; i++) {
        code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return code;
}

// Obtener categorías para el frontend
export function getCategories() {
    return Object.entries(WORD_DATABASE).map(([key, val]) => ({
        id: key,
        name: val.name
    }));
}

// Seleccionar palabra aleatoria de las categorías seleccionadas
export function selectRandomWord(selectedCategories) {
    const categories = selectedCategories.filter(c => WORD_DATABASE[c]);
    if (categories.length === 0) categories.push('animales');
    
    const randomCategoryKey = categories[Math.floor(Math.random() * categories.length)];
    const category = WORD_DATABASE[randomCategoryKey];
    const wordIndex = Math.floor(Math.random() * category.words.length);
    
    // Seleccionar una pista aleatoria de las disponibles para esta palabra
    const hints = category.hints[wordIndex];
    const randomHint = hints[Math.floor(Math.random() * hints.length)];
    
    return {
        word: category.words[wordIndex],
        hint: randomHint,
        categoryName: category.name
    };
}
